@props(['name' => null, 'value' => null, 'label' => null, 'variant' => 'flat', 'color' => 'default', 'size' => 'md', 'radius' => 'md', 'disabled' => false, 'invalid' => false, 'required' => false, 'minValue' => null, 'maxValue' => null, 'locale' => 'ko-KR', 'fullWidth' => false])
@php $range = is_array($value) ? ['start' => $value['start'] ?? $value['from'] ?? '', 'end' => $value['end'] ?? $value['to'] ?? ''] : ['start'=>'','end'=>'']; @endphp
<div data-slot="date-range-picker" data-variant="{{ $variant }}" data-color="{{ $color }}" data-size="{{ $size }}" data-radius="{{ $radius }}" data-disabled="{{ $disabled ? 'true' : 'false' }}" data-invalid="{{ $invalid ? 'true' : 'false' }}" @class(['app-picker',"app-color-$color","app-size-$size","app-radius-$radius",'app-full-width'=>$fullWidth]) {{ $attributes }}>
    @if($label)<span data-slot="label" class="app-field-label">{{ $label }}</span>@endif
    <input type="hidden" data-picker-input value='@json($range)' @required($required)>
    @if($name)<input type="hidden" data-picker-start name="{{ $name }}[start]" value="{{ $range['start'] }}"><input type="hidden" data-picker-end name="{{ $name }}[end]" value="{{ $range['end'] }}">@endif
    <button type="button" data-slot="date-range-picker-trigger" data-variant="{{ $variant }}" data-invalid="{{ $invalid?'true':'false' }}" data-disabled="{{ $disabled?'true':'false' }}" class="app-input-wrapper" aria-haspopup="dialog" aria-expanded="false" @disabled($disabled)><x-icon name="calendar-search-linear" data-slot="start-content" /><span data-picker-display class="app-picker-value">{{ $range['start'] ?: 'YYYY-MM-DD' }} ~ {{ $range['end'] ?: 'YYYY-MM-DD' }}</span></button>
    <div data-slot="date-range-picker-popover" class="app-date-picker-popover" hidden><x-range-calendar :value="$range" :locale="$locale" :min-value="$minValue" :max-value="$maxValue" :visible-months="2" /></div>
</div>
