(function (window, document) {
    'use strict'
    const AppUI = window.AppUI
    const iso = d => [d.getFullYear(), String(d.getMonth()+1).padStart(2,'0'), String(d.getDate()).padStart(2,'0')].join('-')
    const parse = v => v ? new Date(`${v}T00:00:00`) : null
    const read = (el, key, fallback = {}) => { try { return JSON.parse(el.dataset[key]) || fallback } catch { return fallback } }
    const addDays = (value, days) => { const d = parse(value); d.setDate(d.getDate()+days); return iso(d) }
    const calendar = root => {
        const ui = root.querySelector('[data-calendar-ui]'), c = read(root, 'calendarConfig')
        let selected = c.mode === 'range' ? {from: c.value?.from || '', to: c.value?.to || ''} : (c.mode === 'multiple' ? (Array.isArray(c.value) ? c.value : []) : (c.value || ''))
        let month = parse(c.defaultMonth || (c.mode === 'range' ? selected.from : Array.isArray(selected) ? selected[0] : selected)) || new Date(), hover = ''; month.setDate(1)
        const out = value => (c.minDate && value < c.minDate) || (c.maxDate && value > c.maxDate)
        const blocked = value => { const set = Array.isArray(c.disabled) ? c.disabled : [c.disabled]; return set.includes(value) || (typeof c.disabled === 'object' && c.disabled && ((c.disabled.before && value < c.disabled.before) || (c.disabled.after && value > c.disabled.after))) }
        const canNavigate = delta => { const d = new Date(month); d.setMonth(d.getMonth()+delta); const value = iso(d); return !c.disableNavigation && !(c.startMonth && value.slice(0,7) < c.startMonth.slice(0,7)) && !(c.endMonth && value.slice(0,7) > c.endMonth.slice(0,7)) }
        const isPicked = value => c.mode === 'range' ? value === selected.from || value === selected.to : c.mode === 'multiple' ? selected.includes(value) : value === selected
        const renderMonth = panel => {
            const locale = c.locale || undefined, start = new Date(panel); start.setDate(1-((start.getDay()-c.weekStart+7)%7)); const weekdays = Array.from({length:7}, (_,i) => new Intl.DateTimeFormat(locale, {weekday:'short'}).format(new Date(2023,0,1+((i+c.weekStart)%7))))
            let caption = panel.toLocaleDateString(locale, {month:'long',year:'numeric'}), html = `<section class="app-calendar-month"><div class="app-calendar-head"><strong>${caption}</strong></div><div class="app-calendar-grid">${c.showWeekNumber?'<span></span>':''}${weekdays.map(x=>`<span class="app-calendar-weekday">${x}</span>`).join('')}`
            for(let row=0;row<6;row++) { if(c.showWeekNumber) { const d=new Date(start);d.setDate(start.getDate()+row*7); const jan=new Date(d.getFullYear(),0,1); html += `<span class="app-calendar-week">${Math.ceil((((d-jan)/86400000)+jan.getDay()+1)/7)}</span>` } for(let col=0;col<7;col++) { const d=new Date(start);d.setDate(start.getDate()+row*7+col); const value=iso(d), outside=d.getMonth()!==panel.getMonth(), invalid=out(value), disabled=blocked(value)||(invalid&&c.outOfRange!=='flag'), middle=c.mode==='range'&&selected.from&&selected.to&&value>selected.from&&value<selected.to, preview=c.mode==='range'&&selected.from&&!selected.to&&hover&&((selected.from<hover&&value>selected.from&&value<hover)||(hover<selected.from&&value>hover&&value<selected.from)), previewStart=c.mode==='range'&&selected.from&&!selected.to&&hover&&value===(hover<selected.from?hover:selected.from), previewEnd=c.mode==='range'&&selected.from&&!selected.to&&hover&&value===(hover<selected.from?selected.from:hover), rangeStart=c.mode==='range'&&value===selected.from&&(!!selected.to||hover>selected.from), rangeEnd=c.mode==='range'&&value===selected.to, today=value===iso(new Date()); html += outside&&!c.showOutsideDays?'<span class="app-calendar-empty"></span>':`<button type="button" data-day="${value}" class="${outside?'outside ':''}${invalid?'out-of-range ':''}${today?'today ':''}${isPicked(value)?'selected ':''}${rangeStart?'range-start ':''}${rangeEnd?'range-end ':''}${middle?'range-middle ':''}${preview?'range-preview ':''}${previewStart?'range-preview-start ':''}${previewEnd?'range-preview-end ':''}" ${disabled?'disabled':''}>${d.getDate()}</button>` } }
            return html+'</div></section>'
        }
        const render = () => { let html=`<div class="app-calendar-months"><button type="button" class="app-calendar-nav app-calendar-nav-prev" data-prev ${canNavigate(-1)?'':'disabled'} aria-label="Previous month"><span data-slot="icon" data-icon="solar:alt-arrow-left-linear" aria-hidden="true"></span></button><button type="button" class="app-calendar-nav app-calendar-nav-next" data-next ${canNavigate(1)?'':'disabled'} aria-label="Next month"><span data-slot="icon" data-icon="solar:alt-arrow-right-linear" aria-hidden="true"></span></button>`; for(let i=0;i<c.numberOfMonths;i++){const panel=new Date(month);panel.setMonth(panel.getMonth()+i);html+=renderMonth(panel)} ui.innerHTML=html+'</div>' }
        const commit = detail => { root.querySelector('[data-calendar-input]')?.setAttribute('value', JSON.stringify(selected)); root.dispatchEvent(new CustomEvent('calendar:change',{bubbles:true,detail})); render() }
        root.addEventListener('click', e => { const button=e.target.closest('button'); if(!button) return; if(button.matches('[data-prev]')) {month.setMonth(month.getMonth()-1);render();return} if(button.matches('[data-next]')) {month.setMonth(month.getMonth()+1);render();return} const value=button.dataset.day;if(!value) return; if(c.mode==='range'){ let next=!selected.from||selected.to?{from:value,to:''}:value<selected.from?{from:value,to:selected.from}:{from:selected.from,to:value}; const days=next.to?Math.round((parse(next.to)-parse(next.from))/86400000):0; if(next.to&&((c.minDays&&days<Number(c.minDays))||(c.maxDays&&days>Number(c.maxDays))||(c.min&&days<Number(c.min))||(c.max&&days>Number(c.max)))) return root.dispatchEvent(new CustomEvent('calendar:invalid',{bubbles:true,detail:{message:'선택 가능한 기간을 벗어났습니다.'}})); selected=next;hover='';commit(selected) } else if(c.mode==='multiple') { selected=selected.includes(value)?(c.required&&selected.length===1?selected:selected.filter(v=>v!==value)):[...selected,value];commit({value:selected}) } else { if(c.required&&selected===value)return; selected=value;commit({value}) } })
        root.addEventListener('pointerover', e => { const day=e.target.closest('[data-day]')?.dataset.day; if(c.mode==='range'&&selected.from&&!selected.to&&day&&day!==hover){hover=day;render()} })
        root.addEventListener('pointerleave', () => { if(c.mode==='range'&&selected.from&&!selected.to&&hover){hover='';render()} })
        root.addEventListener('calendar:set', e => { selected = c.mode === 'range' ? e.detail : (c.mode === 'multiple' ? e.detail.value : e.detail.value); commit(c.mode === 'range' ? selected : {value:selected}) })
        root.addEventListener('keydown',e=>{const active=e.target.closest('[data-day]');if(!active)return;let offset={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(offset){e.preventDefault();root.querySelector(`[data-day="${addDays(active.dataset.day,offset)}"]`)?.focus()}}); render()
    }
    const datePicker = root => { const pop=root.querySelector('[data-date-popover]'), trigger=root.querySelector('[data-date-trigger]'), cal=root.querySelector('[data-slot="calendar"]'), error=root.querySelector('[data-date-error]'), config=read(root,'dateConfig'); const close=()=>{pop.hidden=true;trigger.setAttribute('aria-expanded','false')}; const invalid=message=>{error.textContent=message;error.hidden=false;trigger.setAttribute('aria-invalid','true')}; trigger.addEventListener('click',()=>{pop.hidden=!pop.hidden;trigger.setAttribute('aria-expanded',String(!pop.hidden))}); root.addEventListener('click',e=>{const p=e.target.closest('[data-date-preset]');if(!p)return;let v=read(p,'datePresetValue',null),today=iso(new Date());if(!v){const keys={today:[today,today],yesterday:[addDays(today,-1),addDays(today,-1)],last7Days:[addDays(today,-6),today],last30Days:[addDays(today,-29),today],thisMonth:[today.slice(0,8)+'01',iso(new Date(new Date().getFullYear(),new Date().getMonth()+1,0))],yearToDate:[today.slice(0,4)+'-01-01',today]};v=keys[p.dataset.datePreset]}const detail=config.mode==='range'?{from:v.from||v[0],to:v.to||v[1]}:{value:v.from||v[0]};cal.dispatchEvent(new CustomEvent('calendar:set',{bubbles:true,detail}))}); cal.addEventListener('calendar:invalid',e=>invalid(e.detail.message)); cal.addEventListener('calendar:change',e=>{error.hidden=true;trigger.removeAttribute('aria-invalid');if(config.mode==='range'){const d=e.detail;root.querySelector('[data-date-from]').value=d.from;root.querySelector('[data-date-to]').value=d.to;const from=root.querySelector('[data-date-from-label]'),to=root.querySelector('[data-date-to-label]');from.textContent=d.from||'YYYY-MM-DD';to.textContent=d.to||'YYYY-MM-DD';from.classList.toggle('is-placeholder',!d.from);to.classList.toggle('is-placeholder',!d.to);if(d.from&&d.to)close()}else{root.querySelector('[data-date-input]')?.setAttribute('value',e.detail.value);const label=root.querySelector('[data-date-value-label]');label.textContent=e.detail.value;label.classList.remove('is-placeholder');close()} }); pop.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.addEventListener('click',e=>{if(!e.composedPath().includes(root))close()}) }
    const timeField = root => { const c=read(root,'timeConfig'), hidden=root.querySelector('[data-time-value]'), ui=root.querySelector('[data-time-ui]'), value=(hidden.value||'').split(':'); const is12=c.hourCycle==='12'||(c.hourCycle==='auto'&&new Intl.DateTimeFormat(undefined,{hour:'numeric'}).resolvedOptions().hourCycle?.startsWith('h12')); const select=(kind,max,step,current)=>`<select data-time-part="${kind}" ${c.disabled?'disabled':''}>${Array.from({length:Math.ceil((max+1)/step)},(_,i)=>{const n=i*step;return `<option value="${String(n).padStart(2,'0')}" ${Number(current)===n?'selected':''}>${String(n).padStart(2,'0')}</option>`}).join('')}</select>`; if(c.inputType==='select'){const hour=Number(value[0]||0), h=is12?(hour%12||12):hour;ui.innerHTML=select('hour',is12?12:23,1,h)+':'+select('minute',59,Math.max(1,c.minuteStep),value[1]||0)+(c.seconds?':'+select('second',59,Math.max(1,c.secondStep),value[2]||0):'')+(is12?`<select data-time-part="ampm"><option ${hour<12?'selected':''}>AM</option><option ${hour>=12?'selected':''}>PM</option></select>`:'')}else{ui.innerHTML=`<input type="time" value="${hidden.value}" min="${c.min||''}" max="${c.max||''}" step="${c.seconds?Math.max(1,c.secondStep):Math.max(1,c.minuteStep)*60}" ${c.disabled?'disabled':''}>`} const sync=()=>{let v;if(c.inputType==='select'){let h=Number(ui.querySelector('[data-time-part="hour"]').value),m=ui.querySelector('[data-time-part="minute"]').value,s=ui.querySelector('[data-time-part="second"]')?.value;if(is12){const pm=ui.querySelector('[data-time-part="ampm"]').value==='PM';h=(h%12)+(pm?12:0)}v=`${String(h).padStart(2,'0')}:${m}${c.seconds?':'+s:''}`}else v=ui.querySelector('input').value;hidden.value=v;root.dispatchEvent(new CustomEvent('time-change',{bubbles:true,detail:{value:v,part:c.part}}))};ui.addEventListener('input',sync);ui.addEventListener('change',sync) }
    AppUI.register('json-viewer','[data-slot="json-viewer"]',root=>{root.addEventListener('click',e=>{const button=e.target.closest('[data-json-toggle]');if(!button)return;const node=button.closest('[data-slot="json-viewer-node"]'),children=node.querySelector(':scope > [data-json-children]'),summary=button.querySelector('[data-json-summary]'),open=children.hidden;children.hidden=!open;summary.hidden=open;button.setAttribute('aria-expanded',String(open));node.dataset.state=open?'open':'closed'})})
    AppUI.register('calendar','[data-slot="calendar"]',calendar); AppUI.register('date-picker','[data-slot="date-picker"]',datePicker); AppUI.register('time-field','[data-slot="time-field"]',timeField)
    AppUI.register('datetime-picker','[data-slot="datetime-picker"]',root=>{const pop=root.querySelector('[data-datetime-popover]'),trigger=root.querySelector('[data-datetime-trigger]'),calendar=root.querySelector('[data-slot="calendar"]'),label=root.querySelector('[data-datetime-label]'),single=root.querySelector('[data-datetime-input]'),from=root.querySelector('[data-datetime-from]'),to=root.querySelector('[data-datetime-to]'),times=[...root.querySelectorAll('[data-slot="time-field"]')],mode=root.dataset.datetimeMode,hourCycle=root.dataset.datetimeHourCycle,showSeconds=root.dataset.datetimeSeconds==='true';let dates=mode==='range'?{from:from?.value.split('T')[0]||'',to:to?.value.split('T')[0]||''}:{value:single?.value.split('T')[0]||''};const close=()=>{pop.hidden=true;trigger.setAttribute('aria-expanded','false')};const format=(date,time)=>{if(!date)return 'YYYY-MM-DD HH:mm';const value=new Date(`${date}T${time||'00:00'}`),options={hour:'2-digit',minute:'2-digit'};if(showSeconds)options.second='2-digit';if(hourCycle!=='auto')options.hourCycle=hourCycle==='12'?'h12':'h23';return `${value.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}, ${value.toLocaleTimeString(undefined,options)}`};const sync=()=>{const values=times.map(field=>field.querySelector('[data-time-value]').value);if(mode==='range'){const start=dates.from?(dates.from+'T'+(values[0]||'00:00')):'',end=dates.to?(dates.to+'T'+(values[1]||'00:00')):'';if(from)from.value=start;if(to)to.value=end;label.textContent=`${format(dates.from,values[0])} ~ ${format(dates.to,values[1])}`}else{const value=dates.value?(dates.value+'T'+(values[0]||'00:00')):'';if(single)single.value=value;label.textContent=dates.value?format(dates.value,values[0]):'YYYY-MM-DD HH:mm'}};trigger.addEventListener('click',()=>{pop.hidden=!pop.hidden;trigger.setAttribute('aria-expanded',String(!pop.hidden))});calendar?.addEventListener('calendar:change',e=>{dates=mode==='range'?e.detail:{value:e.detail.value};sync()});root.addEventListener('time-change',sync);root.querySelector('[data-datetime-done]')?.addEventListener('click',close);pop.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.addEventListener('click',e=>{if(!e.composedPath().includes(root))close()});sync()})
    AppUI.register('image','[data-slot="image"]',root=>{const image=root.querySelector('[data-image-main]'),placeholder=root.querySelector('[data-image-placeholder]'),error=root.querySelector('[data-image-error]');const loaded=()=>{root.dataset.state='loaded';image.hidden=false;placeholder.hidden=true;error.hidden=true};const failed=()=>{root.dataset.state='error';image.hidden=true;placeholder.hidden=true;error.hidden=false};image.addEventListener('load',loaded);image.addEventListener('error',failed);if(image.complete)queueMicrotask(()=>image.naturalWidth>0?loaded():failed())})
})(window,document)
