(function (window, document) {
    'use strict'
    const AppUI = window.AppUI
    const pad = value => String(value).padStart(2,'0')
    const iso = date => `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`
    const parse = value => { if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;const [year,month,day]=value.split('-').map(Number),date=new Date(year,month-1,day);return date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day?date:null }
    const addMonths = (date, amount) => new Date(date.getFullYear(),date.getMonth()+amount,1)
    const between = (value,start,end) => start&&end&&value>start&&value<end

    AppUI.register('date-input','[data-slot="date-input"],[data-slot="time-input"]',root=>{
        const hidden=root.querySelector('[data-date-value]'),segments=[...root.querySelectorAll('[data-date-segment]')]
        const compose=()=>segments.map(segment=>segment.value.padStart(Number(segment.maxLength||2),'0')).join(root.dataset.slot==='time-input'?':':'-')
        const sync=notify=>{hidden.value=compose();if(notify){hidden.dispatchEvent(new Event('input',{bubbles:true}));hidden.dispatchEvent(new Event('change',{bubbles:true}));AppUI.emit(root,`${root.dataset.slot}:change`,{value:hidden.value})}}
        segments.forEach((segment,index)=>{segment.addEventListener('input',()=>{segment.value=segment.value.replace(/\D/g,'').slice(0,segment.maxLength);if(segment.value.length===Number(segment.maxLength))segments[index+1]?.focus();sync(true)});segment.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'&&segment.selectionStart===0)segments[index-1]?.focus();if(event.key==='ArrowRight'&&segment.selectionStart===segment.value.length)segments[index+1]?.focus();if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();const min=Number(segment.min||0),max=Number(segment.max||99),next=Math.min(max,Math.max(min,Number(segment.value||min)+(event.key==='ArrowUp'?1:-1)));segment.value=pad(next);sync(true)}})});
        return{getValue:()=>hidden.value,setValue:value=>{String(value||'').split(root.dataset.slot==='time-input'?':':'-').forEach((part,index)=>{if(segments[index])segments[index].value=part});sync(false)},focus:()=>segments[0]?.focus()}
    })

    AppUI.register('calendar','[data-slot="calendar"]',root=>{
        const config=JSON.parse(root.dataset.calendarConfig||'{}'),locale=config.locale||document.documentElement.lang||'ko-KR',mode=config.selectionMode||'single',input=root.querySelector('[data-calendar-input]'),ui=root.querySelector('[data-calendar-ui]')
        let current=parse(config.visibleMonth)||parse(mode==='range'?(config.value?.start||config.value?.from):config.value)||new Date(),hovered=''
        current=new Date(current.getFullYear(),current.getMonth(),1)
        let selected=mode==='range'?{start:String(config.value?.start||config.value?.from||''),end:String(config.value?.end||config.value?.to||'')}:(mode==='multiple'?(config.value||[]).map(String):String(config.value||''))
        const min=parse(config.minValue),max=parse(config.maxValue),weekStart=Number(config.firstDayOfWeek??0),months=Math.max(1,Number(config.visibleMonths||1))
        const disabled=value=>{const date=parse(value);return !date||(min&&date<min)||(max&&date>max)||(config.disabledValues||[]).includes(value)}
        const emit=()=>{if(input)input.value=mode==='range'?JSON.stringify(selected):mode==='multiple'?JSON.stringify(selected):selected;AppUI.emit(root,'calendar:change',{value:selected})}
        const focusValue=value=>{let target=ui.querySelector(`[data-value="${value}"]`);if(target){target.tabIndex=0;target.focus();return}const date=parse(value);if(!date)return;current=new Date(date.getFullYear(),date.getMonth(),1);render();requestAnimationFrame(()=>ui.querySelector(`[data-value="${value}"]`)?.focus())}
        const choose=value=>{if(disabled(value))return;if(mode==='range'){if(!selected.start||selected.end){selected={start:value,end:''}}else if(value<selected.start){selected={start:value,end:selected.start}}else selected.end=value}else if(mode==='multiple'){selected=selected.includes(value)?selected.filter(item=>item!==value):[...selected,value]}else selected=value;hovered='';render();emit();requestAnimationFrame(()=>focusValue(value))}
        const renderMonth=(monthDate,index)=>{const year=monthDate.getFullYear(),month=monthDate.getMonth(),first=new Date(year,month,1),offset=(first.getDay()-weekStart+7)%7,days=new Date(year,month+1,0).getDate(),previousDays=new Date(year,month,0).getDate(),formatter=new Intl.DateTimeFormat(locale,{month:'long',year:'numeric'}),weekdays=Array.from({length:7},(_,day)=>new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(2024,0,7+((day+weekStart)%7))))
            const monthEl=document.createElement('section');monthEl.className='app-calendar-month';monthEl.innerHTML=`<div class="app-calendar-header">${index===0?'<button type="button" class="app-calendar-nav" data-calendar-prev aria-label="Previous month">‹</button>':'<span></span>'}<strong class="app-calendar-title">${formatter.format(monthDate)}</strong>${index===months-1?'<button type="button" class="app-calendar-nav" data-calendar-next aria-label="Next month">›</button>':'<span></span>'}</div><div class="app-calendar-grid">${weekdays.map(day=>`<span class="app-calendar-weekday">${day}</span>`).join('')}</div>`
            const grid=monthEl.querySelector('.app-calendar-grid'),total=Math.ceil((offset+days)/7)*7
            for(let cell=0;cell<total;cell++){const day=cell-offset+1;let date,outside=false;if(day<1){date=new Date(year,month-1,previousDays+day);outside=true}else if(day>days){date=new Date(year,month+1,day-days);outside=true}else date=new Date(year,month,day);const value=iso(date),button=document.createElement('button');button.type='button';button.className='app-calendar-cell';button.textContent=String(date.getDate());button.dataset.value=value;button.dataset.outside=String(outside);button.dataset.today=String(value===iso(new Date()));button.dataset.disabled=String(disabled(value));let isSelected=false,middle=false;if(mode==='range'){isSelected=value===selected.start||value===selected.end;const previewEnd=selected.start&&!selected.end?hovered:'';middle=between(value,selected.start,selected.end||previewEnd)}else isSelected=mode==='multiple'?selected.includes(value):selected===value;button.dataset.selected=String(isSelected);button.dataset.rangeMiddle=String(middle);button.setAttribute('aria-label',new Intl.DateTimeFormat(locale,{dateStyle:'full'}).format(date));button.setAttribute('aria-pressed',String(isSelected));if(disabled(value))button.disabled=true;button.addEventListener('click',()=>choose(value));button.addEventListener('pointerenter',()=>{if(mode==='range'&&selected.start&&!selected.end&&hovered!==value){hovered=value;render()}});grid.appendChild(button)}return monthEl}
        const render=()=>{ui.replaceChildren();const monthsWrap=document.createElement('div');monthsWrap.style.display='flex';monthsWrap.style.gap='1rem';for(let index=0;index<months;index++)monthsWrap.appendChild(renderMonth(addMonths(current,index),index));ui.appendChild(monthsWrap);const cells=[...ui.querySelectorAll('.app-calendar-cell:not(:disabled)')];cells.forEach(cell=>cell.tabIndex=-1);const activeValue=mode==='range'?(selected.end||selected.start):mode==='multiple'?selected.at(-1):selected;const active=cells.find(cell=>cell.dataset.value===activeValue)||cells.find(cell=>cell.dataset.today==='true')||cells[0];if(active)active.tabIndex=0;ui.querySelector('[data-calendar-prev]')?.addEventListener('click',()=>{current=addMonths(current,-1);render()});ui.querySelector('[data-calendar-next]')?.addEventListener('click',()=>{current=addMonths(current,1);render()})}
        root.addEventListener('keydown',event=>{const cell=event.target.closest('.app-calendar-cell');if(!cell)return;const date=parse(cell.dataset.value);if(!date)return;let next=null;if(event.key==='ArrowLeft')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()-1);if(event.key==='ArrowRight')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()+1);if(event.key==='ArrowUp')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()-7);if(event.key==='ArrowDown')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()+7);if(event.key==='Home')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()-((date.getDay()-weekStart+7)%7));if(event.key==='End')next=new Date(date.getFullYear(),date.getMonth(),date.getDate()+(6-(date.getDay()-weekStart+7)%7));if(event.key==='PageUp')next=new Date(date.getFullYear(),date.getMonth()-1,date.getDate());if(event.key==='PageDown')next=new Date(date.getFullYear(),date.getMonth()+1,date.getDate());if(next){event.preventDefault();focusValue(iso(next))}})
        root.addEventListener('pointerleave',()=>{if(hovered){hovered='';render()}});render()
        return{getValue:()=>selected,setValue:value=>{selected=value;render()},focus:()=>ui.querySelector('[data-today="true"]')?.focus(),next:()=>{current=addMonths(current,1);render()},previous:()=>{current=addMonths(current,-1);render()}}
    })

    const registerPicker=(name,root)=>{const trigger=root.querySelector(`[data-slot="${name}-trigger"]`),popover=root.querySelector(`[data-slot="${name}-popover"]`),calendar=popover?.querySelector('[data-slot="calendar"]'),display=root.querySelector('[data-picker-display]'),input=root.querySelector('[data-picker-input]'),startInput=root.querySelector('[data-picker-start]'),endInput=root.querySelector('[data-picker-end]');if(!trigger||!popover||!calendar)return{};AppUI.interaction(root);const overlay=AppUI.overlay.create({root,trigger,panel:popover,placement:'bottom-start',matchWidth:false});const sync=(value,notify=true)=>{input.value=typeof value==='string'?value:JSON.stringify(value);if(startInput)startInput.value=value.start||'';if(endInput)endInput.value=value.end||'';display.textContent=typeof value==='string'?value:`${value.start||'YYYY-MM-DD'} ~ ${value.end||'YYYY-MM-DD'}`;if(notify){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));AppUI.emit(root,`${name}:change`,{value})}};calendar.addEventListener('app-ui:calendar:change',event=>{const value=event.detail.value;sync(value);if(typeof value==='string'||value.end)overlay.close(true)});root.dataset.uiComponent=name;return{getValue:()=>{try{return JSON.parse(input.value)}catch{return input.value}},setValue:value=>{calendar.appUI?.setValue(value);sync(value)},open:overlay.open,close:overlay.close,focus:()=>trigger.focus()}}
    AppUI.register('date-picker','[data-slot="date-picker"]',root=>registerPicker('date-picker',root))
    AppUI.register('date-range-picker','[data-slot="date-range-picker"]',root=>registerPicker('date-range-picker',root))
})(window, document)
